#ifndef CRAYONMODBUSPLUGIN_GLOBAL_H
#define CRAYONMODBUSPLUGIN_GLOBAL_H
#include <QtCore/qglobal.h>

#if defined(CRAYON_MODBUS_LIBRARY)
#  define CRAYON_MODBUS_EXPORT Q_DECL_EXPORT
#else
#  define CRAYON_MODBUS_EXPORT Q_DECL_IMPORT
#endif
#endif // CRAYONMODBUSPLUGIN_GLOBAL_H
