#ifndef CRAYONSTANDARTPLUGIN_GLOBAL_H
#define CRAYONSTANDARTPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CRAYON_STANDART_LIBRARY)
#  define CRAYON_STANDART_EXPORT Q_DECL_EXPORT
#else
#  define CRAYON_STANDART_EXPORT Q_DECL_IMPORT
#endif

#endif // CRAYONSTANDARTPLUGIN_GLOBAL_H
